### ISSUE TITLE
create an incremental table with the sdk

### ISSUE THREAD

**Issue by Milk-Tang** [cloudquery/plugin-sdk#1001]
### Are you positive this feature should be implemented in the SDK?

- [X] I'm positive this is an SDK feature

### Which problem is this feature request solving?

I'd like to create a incremental table of source plugin, how can I do it?

### Describe the solution you'd like

.

### Pull request (optional)

- [ ] I can submit a pull request

**Comment by hermanschaaf** [comment]
Hi @Milk-Tang, while we don't currently have a guide written for developing incremental source tables, I would recommend you check out the Hacker News plugin resolver: 
 - Resolver: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/hackernews/resources/services/items/items_fetch.go
 - Table definition: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/hackernews/resources/services/items/items.go

It is very thoroughly commented, so it acts as a kind of tutorial that is guaranteed to be up-to-date with the latest SDK. 

Also I just want to note that incremental table support is currently still experimental, and we are working on an SDK update that will change the interface somewhat (for the better!). Once SDK v4 is released you will need to make some updates, but again you'd be able to use the HN plugin as a reference for how to do that.

**Comment by Milk-Tang** [comment]
> Hi @Milk-Tang, while we don't currently have a guide written for developing incremental source tables, I would recommend you check out the Hacker News plugin resolver:
> 
> * Resolver: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/hackernews/resources/services/items/items_fetch.go
> * Table definition: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/hackernews/resources/services/items/items.go
> 
> It is very thoroughly commented, so it acts as a kind of tutorial that is guaranteed to be up-to-date with the latest SDK.
> 
> Also I just want to note that incremental table support is currently still experimental, and we are working on an SDK update that will change the interface somewhat (for the better!). Once SDK v4 is released you will need to make some updates, but again you'd be able to use the HN plugin as a reference for how to do that.

Thank you for your help. I will refer to it!
