### ISSUE TITLE
Consider making column resolver a requirement

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#198]
With the new template based codegen we generate `PathResolver` for all columns using field names, so extracting fields always works.

Also we still have the fallback of using `ToPascal` on the column name to try and extract values:
https://github.com/cloudquery/plugin-sdk/blob/38103092cf1de9a56c5c191f213d779cd74eab43/schema/table.go#L229

We've seen casing conversions can be hard to get quite right, and we can only catch such mistakes if we have unit/mock tests for all plugins and all tables.

Should we make `column.Resolver` mandatory? That way plugin authors must configure how data is extracted and we don't rely on a convention that only works some of the time

**Comment by yevgenypats** [comment]
Im on the fence here but if we do that then we actually would need to change the column interface as do breaking changes in runtime. The current one is mostly with everything as optional and it is just accessed as struct but if we are looking to adding required parameter then we should catch it in compile time and for this we need to have a new interface such as `NewColumn(name, columnresolver, ...ColumnOption)` which can also be quite alot of boilerplate code (even though it is generated)

**Comment by erezrokah** [comment]
Got it, I think what troubles me with the current implementation is that we assume `ToPascal` on the column name gives us the struct field name, which we've seen doesn't work in enough cases to justify always overriding it.

> The current one is mostly with everything as optional and it is just accessed as struct but if we are looking to adding required parameter then we should catch it in compile time and for this we need to have a new interface such as `NewColumn(name, columnresolver, ...ColumnOption)` which can also be quite alot of boilerplate code (even though it is generated)

Maybe we should change as `Name` and `Type` are basically a requirement too and we don't enforce them

**Comment by erezrokah** [comment]
Closing as wontfix for now
