### ISSUE TITLE
Should the SDK handle downloading plugins?

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#222]
Looks like https://github.com/cloudquery/plugin-sdk/pull/208 moved the code that downloads plugins from the CLI to the SDK.

I'm not sure the SDK should be aware to how we structure our releases in the monorepo. We basically have a circular dependency now.

Also since we download plugins in the SDK, we lost the progress bar during download.
Also since our releases are a bit different on multiple OSes, we'll need to add cross platform tests for the SDK.

Relevant code in https://github.com/cloudquery/plugin-sdk/blob/11b75eb17b7cee0dfb2d56e48597f01840f01c5c/clients/download.go#L21

**Comment by yevgenypats** [comment]
We didn't lost the progress bar as it is available via `writers` interface.

Regarding circular dependency - you are correct but I think it's not a big deal as this should never change mostly.

**Comment by erezrokah** [comment]
> We didn't loose the progress bar as it is available via `writers` interface.

Is this implemented? Because I don't see the progress bar. Do you mean we'll need to add it here:
https://github.com/cloudquery/cloudquery/blob/1af9ec438770ff660ed1141c6e43b5b02426a01a/cli/cmd/sync.go#L69
as an option? If so I'll open an issue for it, as GitHub downloads can be a bit slow sometimes and right now if you configure multiple plugins (like `aws,gcp,azure`) together it just looks like the CLI hangs.

**Comment by erezrokah** [comment]
> Regarding circular dependency - you are correct but I think it's not a big deal as this should never change mostly.

Was there a specific reason to put the download code in the SDK? It makes it very hard to test releases and also test on multiple environments (we'll probably need to have cross env tests both in the CLI and in the SDK).

Maybe the SDK can have only `RegistryGrpc` and `RegistryLocal` and the CLI can deal with version management, and create a new local plugin after downloading it?

**Comment by yevgenypats** [comment]
yes exactly. an issue will work.

Yes - there is no perfect place to put this part I tried several ways and some ended up duplicating a lot of code and making the CLI complex. If it will become an issue we can always move it back. let's keep it this way for a while.

**Comment by erezrokah** [comment]
>If it will become an issue we can always move it back

I think it already is a maintenance issue 🙃 
Some challenges with having a circular dependency:
1. Where should we put cross env tests? Both CLI and SDK? So the SDK should have a test that downloads the CLI? 
2. Let's say we bring back the `gen` command for the sake of getting the latest version. Should that be in the CLI or the SDK?
3. How do we make a change to our release pipeline and test it? Currently we'll need make a change in the CLI codebase, then publish releases, then update the SDK code, then publish an SDK release, then update the CLI with the new SDK to ensure it works.

I 💯 agree that the client interface and connecting to plugins should be in the SDK. My suggestion is to only keep the download versions part in the CLI.

I do think there will be changes to the way we download versions soon, especially for community plugins, as we didn't test that part nor documented the conventions for it.

A simple way to change only the download part is to rename `RegistryGithub` to `RegistryRemote` and then pass a version fetch as an option, WDYT?

**Comment by erezrokah** [comment]
> The downloading logic is part of the goreleaser and not really imported by either the CLI nor the plugins.

I think the circular dependency is as the repository level, not at the module level. It means that instead of doing the change in a single repository, you need to do it in multiple repositories, and in several steps, for example instead of:

1. Change releaser
2. Change CLI

We need:
1. Change releaser
2. Change SDK
3. Publish SDK
4. Update CLI with new SDK

Now if something doesn't work in the process (which often is with release changes), the dev cycle is longer.

Maybe better to discuss live as I still don't understand the benefit of having the download logic in the SDK.

**Comment by erezrokah** [comment]
Looks like we've moved handling the progress bard to the SDK altogether:
https://github.com/cloudquery/plugin-sdk/pull/238
https://github.com/cloudquery/plugin-sdk/pull/240
https://github.com/cloudquery/plugin-sdk/pull/248
https://github.com/cloudquery/plugin-sdk/pull/250

Having the SDK write directly to `stdout` is a bit fragile (especially with a progress bard that overwrites the terminal) as it's hard to enforce a convention preventing the SDK from breaking the CLI output.

**Comment by erezrokah** [comment]
Closing as `wontfix` for now as it's low priority. We can re-visit in the future
