### ISSUE TITLE
Parallelization of Detail Calls 

### ISSUE THREAD

**Issue by bbernays** [cloudquery/plugin-sdk#264]
Using `PreResourceResolver` should enable all of the resolvers to be invoked in parallel (with concurrency guardrails) this is impacting user experience that are fetching resources that require the list/detail pattern: https://github.com/cloudquery/cloudquery/issues/2392

This functionality is also blocking the full removal of the ListDetail pattern in the AWS Plugin: https://github.com/cloudquery/cloudquery/pull/2460

**Comment by yevgenypats** [comment]
Solved with https://github.com/cloudquery/plugin-sdk/pull/268
