### ISSUE TITLE
chore(ci): Add protobuf linting

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#297]
Looks like we can detect breaking changes to the protocol via https://docs.buf.build/ci-cd/github-actions

**Comment by yevgenypats** [comment]
I took a quick look at buf.build https://github.com/bufbuild/buf seems a bit of an overkill but didn't give it a try. do we really need this, also wasn't sure if it's paid or not?

**Comment by erezrokah** [comment]
Yeah, I was hoping this could be a nice new contribution. Since no one picked it up let's close this
