### ISSUE TITLE
listAndValidateTables should not return child tables

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/plugin-sdk#340]
`listAndValidateTables` can in some circumstances return child tables right now, and this will probably cause a panic. We should either disallow child tables from being listed in the config, or filter the child tables out before returning the list if their parents are included (or both)

See comment here for details: https://github.com/cloudquery/plugin-sdk/pull/339#discussion_r1012748251_

**Comment by disq** [comment]
It causes the resolver for the child table to be called with a `nil` `parent` which causes a panic, yes.

**Comment by disq** [comment]
I think child tables should be disallowed in the config.
