### ISSUE TITLE
feature: Allow selective child-table filtering/inclusion

### ISSUE THREAD

**Issue by disq** [cloudquery/plugin-sdk#344]
If a resource has many child tables and the user just wants a few synced, they should be able to achieve that by including those tables (and possibly all their dependent parent tables, if we don't want implicit behaviour) in the config.

This is the opposite of #340 but needs more changes in the handling side of things, not just input validation.

**Comment by erezrokah** [comment]
I think we can close this with https://github.com/cloudquery/plugin-sdk/pulls?q=is%3Apr+is%3Aclosed WDYT?

**Comment by hermanschaaf** [comment]
Yes, support for this was added in https://github.com/cloudquery/plugin-sdk/pull/398

**Comment by hermanschaaf** [comment]
(It is also documented in some detail here: https://cloudquery-qqows19kq-cloudquery.vercel.app/docs/advanced-topics/performance-tuning)
