### ISSUE TITLE
feature: Support cursor-based syncing

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/plugin-sdk#413]
It has come up a couple of times that it would be good for the SDK to support cursor-based syncing. For APIs that allow it, this would allow resources to be fetched once, with only updates being fetched after the first sync. For some resource types, this optimization would be a significant performance boost.

This would be especially useful in cases where the APIs allow for time-based querying, and it is known that resources never change once they are created (like logs, reports, audit trails).

One concrete example where this would be beneficial is the Heroku audit trail event: https://devcenter.heroku.com/articles/platform-api-reference#audit-trail-event . It allows querying by day, so an optimized implementation would only fetch historical days the first time, then in subsequent runs fetch the days that have been added since the previous sync.

**Comment by hermanschaaf** [comment]
> This will require persisting the last sync timestamp (we already do that) and then executing query beforehand.

Yes, though I think we should generalize it by allowing each table to specify which column should be used. In most cases this would be a strictly increasing ID column or a timestamp. This column should then be queried for the highest value, and subsequent queries started from there onwards.

**Comment by candiduslynx** [comment]
I suppose, a tuple with both timestamp & some increasing ID would be the most generic.
We can use [snowflakes](https://en.wikipedia.org/wiki/Snowflake_ID), too.
