### ISSUE TITLE
Refactor code related to flattenened tables

### ISSUE THREAD

**Issue by hermanschaaf** [cloudquery/plugin-sdk#470]
Flattened lists of tables have caused a few bugs now, because once they are returned it's hard to know what kind of list you are working with. Is it a flattened list or a normal list? Calling code that expects one but not the other can cause issues like tables getting traversed twice.

`listAndValidateTables` is one example of a function that returns a flattened list, and has so far been the main culprit https://github.com/cloudquery/plugin-sdk/blob/7474c90415119082bdb1cdb145bd16d1ef51a3b2/plugins/source_validate.go#L33

Flattened lists of tables are useful, but we should clearly distinguish flattened lists of tables from normal top-level lists. My reading is that we currently only use flattened lists for two things:
 - getting the total number of tables
 - checking if a table is in the top-level list by using `GetTopLevel`

These two things can both be achieved by a "set" type. If `listAndValidateTables` returned an abstracted "set" type that hid its internals and exposed only two methods: `Size() int` and `Contains(table) bool`, most of the bugs we've had so far would have been avoided. I think we should try to refactor the code to work something along those lines, so that it is easier to reason about and harder to make mistakes.

**Comment by hermanschaaf** [comment]
I realized now that we have another bug related to this 😮‍💨 

Initially `TableForSpec` returned a flattened list. This led to bugs in some destination plugins that flattened the list a second time. So we updated `TableForSpec` to match `Tables` in returning a top-level list. This fixed the immediate bug, but it was a mistake, because now we have no way of telling whether a child table was specifically selected or not. The consequence is that child relations of selected tables will always be migrated, and will always be cleared of  stale data, even when those child relations are skipped by config.

I think that the original `TablesForSpec` implementation was correct: it _should_ return a flattened list, but we should use a different type (like a set) to distinguish it. Callers should then call `Tables()` for the full list of available tables

---

The core of the issue is this: we have a forest (multiple of trees) structure of tables:

```
A         E
|  \        |
B  C    F
|
D
```

We need to be able to convey information about which of these tables the user intended to select. Let's say the user wants to select `A`, `E` and `F`, but none of `A`'s children. A flattened list would convey it like this:

```
[A, E, F]
```

(with links to child tables still in tact) but the list is hard to distinguish from a list of all top-level tables:

```
[A, E]
```

and right now `TableForSpec` returns `[A, E]`, so information about which descendant tables should be synced is lost.

If we had a set, we could write the user's choice like this:

```
{A, E, F}
```

This is easily distinguishable from a top-level list, because it's a different type. I think we should keep this set dead-simple, so that any traversal requires the forest structure. The set should probably just contain the table names, nothing else.

Clients that need to know the full table structure should then call `Tables()` to get it, and `TablesForSpec()` to know the subset of tables selected by the user. Clients that don't need the full structure (only the names of selected tables), can only call `TablesForSpec()`, but if they want any details about tables, they'll still need to call `Tables()` first.

**Comment by yevgenypats** [comment]
Solved by https://github.com/cloudquery/plugin-sdk/pull/488
