### ISSUE TITLE
batch per tables

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/plugin-sdk#507]
### Describe the bug

Right now we implement batching in all plugins and this cause number of issues:
1) batching is mostly implemented on a X resource basis and not per table. This will mean that if there is an issue in one table it can affect all others instead of affecting just a single one.

The solution to that will be implementing batching on the SDK level for destinations.

**Comment by erezrokah** [comment]
Also opened https://github.com/cloudquery/cloudquery/issues/5679 which I now closed, but I think we could look into adding a similar retry mechanism to exclude the failed resource from the batch (or retry with batch size 1 on failure)

**Comment by yevgenypats** [comment]
Done with https://github.com/cloudquery/cloudquery/pull/5805
