### ISSUE TITLE
Discussion(testing): Improve PK validation in tests

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#591]
Coming from [all the PK fixes in GCP](https://github.com/cloudquery/cloudquery/issues?q=author%3Aerezrokah+pk+OR+pks+label%3Agcp) I was wondering if we can improve our PK validation.

In the above fixes the issues are:

1. Missing PK configuration and defaulting to `_cq_id`. I don't think the SDK can validate this as it's OK to not have a PK configured
2. Using a non struct field (like `project_id` or a parent field like [here](https://github.com/cloudquery/cloudquery/pull/6550/files)) as the only PK. We could try and validate this by faking more than 1 item per array, with different data per item and assert that multiple entries are written
3. Using a struct field that's not unique like [here](https://github.com/cloudquery/cloudquery/pull/6544). I don't think the SDK can validate this

Thoughts? I'm leaning to not do anything about this

**Comment by yevgenypats** [comment]
I think I would continue not to do anything at this stage. maybe later we can introduce some kind of custom validation a plugin can introduce or something like that but I feel it's a bit too early and I couldn't think of a solution in mind that I really like.

**Comment by erezrokah** [comment]
Cool, closing the issue for now
