### ISSUE TITLE
feat: Extract `ManagedWriter` to helper package, use single `Write()` for destinations

### ISSUE THREAD

**Issue by disq** [cloudquery/plugin-sdk#858]
### Are you positive this feature should be implemented in the SDK?

- [X] I'm positive this is an SDK feature

### Which problem is this feature request solving?

Currently the `ManagedWriter` is built-in in the SDK which makes it impossible to extend or swap it with another implementation without changing/breaking the SDK.

### Describe the solution you'd like

Let's make the destinations specify their own 'custom writers' if they want to, something like: `destination.WithManagedWriter(<some constructor or interface>)` so that it can be swapped out or injected from an external package. We can still supply the traditional ManagedWriter as an helper package in the SDK.

### Pull request (optional)

- [x] I can submit a pull request

**Comment by candiduslynx** [comment]
This needs to be done after moving the PK dup filter to the source side, as the managed writer is the only place ATM to do so.

**Comment by disq** [comment]
@candiduslynx It can be an option to the constructor, dedup or not, so the choice remains in the destination side.

**Comment by yevgenypats** [comment]
Done in SDK V4
